#!/usr/bin/env bash
#
# Validates a branch name against the conventions in CONTRIBUTING.md#branch-naming.
#
# Usage:
#   scripts/checks/branch-name.sh            # validate the current branch
#   scripts/checks/branch-name.sh <branch>   # validate the given branch name

set -euo pipefail
export LC_ALL=C

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/conventions.sh
. "$here/../lib/conventions.sh"

branch="${1:-}"
if [ -z "$branch" ]; then
  branch="$(git symbolic-ref --short -q HEAD || true)"
  if [ -z "$branch" ]; then
    warn "Detached HEAD; nothing to check."
    exit 0
  fi
fi

if [ "$branch" = "main" ]; then
  fail "You are on 'main'. Work on a branch: git switch -c <type>/<issue>-<short-description>"
  exit 1
fi

# The agent loop's integration branch, valid as the head of a promotion PR into main
# (ADR 0010). The git hooks and the Claude Code hook block committing and pushing to it.
if [ "$branch" = "agent-main" ]; then
  ok "Branch 'agent-main' is the agent loop's integration branch."
  exit 0
fi

# Branches generated by tools.
case "$branch" in
  dependabot/* | revert-* | claude/*)
    ok "Branch '$branch' is a tool-generated branch."
    exit 0
    ;;
esac

types="$(types_regex)"
human_regex="^(${types})/([0-9]+-)?${SLUG_REGEX}$"
agent_regex="^agent/${AGENT_NAME_REGEX}/(${types})/([0-9]+-)?${SLUG_REGEX}$"

if [ "${#branch}" -gt "$BRANCH_MAX_LENGTH" ]; then
  fail "Branch name is ${#branch} characters; the maximum is $BRANCH_MAX_LENGTH."
  exit 1
fi

if [[ "$branch" =~ $human_regex ]] || [[ "$branch" =~ $agent_regex ]]; then
  ok "Branch name '$branch' follows the conventions."
  exit 0
fi

fail "Branch name '$branch' does not follow the conventions."
cat >&2 <<EOF

  Expected one of:
    <type>/<issue>-<short-description>              feat/12-safety-policy-schema
    <type>/<short-description>                      docs/add-memory-style-guide
    agent/<agent>/<type>/<issue>-<description>      agent/improver/fix/40-tighten-dor-rules

  <type>:   ${CONVENTIONAL_TYPES}
  <agent>:  orchestrator | improver | habit-<habit-name>
  Lowercase kebab-case only (a-z, 0-9, -).

  Rename with: git branch -m <new-name>
  See ${CONTRIBUTING_URL}#branch-naming
EOF
exit 1
